# Generated by Django 4.2.7 on 2025-05-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_type', models.CharField(choices=[('PREVIOUS', 'Previous Year'), ('CURRENT_1', 'Current Year - List 1'), ('CURRENT_2', 'Current Year - List 2'), ('CURRENT_3', 'Current Year - List 3')], max_length=20)),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], max_length=20)),
                ('cutoff_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available_seats', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='colleges.stream')),
            ],
            options={
                'ordering': ['-year', 'stream', 'category'],
                'unique_together': {('stream', 'cutoff_type', 'year', 'category')},
            },
        ),
    ]
