# Generated by Django 4.2.7 on 2025-05-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutoffs', '0002_cutoff_closing_rank_cutoff_opening_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutoff',
            name='opening_rank',
        ),
    ]
