# Generated by Django 4.2.7 on 2025-05-30 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=20, unique=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SELECTED_LIST_1', 'Selected in List 1'), ('SELECTED_LIST_2', 'Selected in List 2'), ('SELECTED_LIST_3', 'Selected in List 3'), ('REJECTED', 'Rejected'), ('ADMITTED', 'Admitted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('documents_verified', models.BooleanField(default=False)),
                ('fees_paid', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='colleges.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
                'unique_together': {('student', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('academic_year', models.CharField(max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admissions.application')),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('LIST_1', 'Merit List 1'), ('LIST_2', 'Merit List 2'), ('LIST_3', 'Merit List 3'), ('FINAL', 'Final Admission List')], max_length=10)),
                ('year', models.IntegerField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applications', models.ManyToManyField(related_name='admission_lists', to='admissions.application')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_lists', to='colleges.stream')),
            ],
            options={
                'ordering': ['-year', 'stream', 'list_type'],
                'unique_together': {('stream', 'list_type', 'year')},
            },
        ),
    ]
