# Generated by Django 4.2.7 on 2025-06-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_email_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
    ]
