# Generated by Django 4.2.7 on 2025-05-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('established_year', models.IntegerField()),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='college_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream_type', models.CharField(choices=[('SCIENCE', 'Science'), ('COMMERCE', 'Commerce'), ('ARTS', 'Arts'), ('ENGINEERING', 'Engineering'), ('MEDICAL', 'Medical'), ('LAW', 'Law'), ('MANAGEMENT', 'Management')], max_length=20)),
                ('duration_years', models.IntegerField()),
                ('total_seats', models.IntegerField()),
                ('fees_per_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eligibility_criteria', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='colleges.college')),
            ],
            options={
                'ordering': ['college', 'name'],
                'unique_together': {('college', 'name')},
            },
        ),
    ]
