# Generated by Django 4.2.7 on 2025-05-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_college_closing_rank_college_opening_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='opening_rank',
        ),
    ]
